# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: sqlite3
  encoding: unicode
  database: bfdb_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: bfdb_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: bfdb
  pool: 5


# development:
#   adapter: postgresql
#   encoding: unicode
#   database: bfdb_development
#   pool: 5
#   username: bfdude
#   password: 

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: bfdb_test
#   pool: 5
#   username: bfdude
#   password: 

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: bfdb
#   pool: 5
#   username: bfdude
#   password: 
